'use client'

import { useMemo, useState } from 'react'
import {
  Activity, ArrowUpRight, BarChart3, Bell, BookOpen, Bot, BrainCircuit, Check, ChevronDown, CircleHelp, Database, FileText, Filter, FolderKanban, Gauge, GitCompare, Hexagon, LayoutDashboard, Lightbulb, Menu, Moon, MoreHorizontal, Network, Plus, Search, Settings, ShieldCheck, Sparkles, Sun, Trash2, Upload, Users, X, Zap,
} from 'lucide-react'

type View = 'overview' | 'workspaces' | 'workspace-detail' | 'documents' | 'document-detail' | 'map' | 'insights' | 'evidence' | 'claim' | 'assistant' | 'saved' | 'settings'

type Document = { title: string; source: string; pages: number; status: 'Indexed' | 'Processing'; topics: string[]; date: string }

const documents: Document[] = [
  { title: 'Foundation Models for Clinical Decision Support', source: 'Nature Medicine · 2024', pages: 18, status: 'Indexed', topics: ['Clinical AI', 'LLMs'], date: 'Today' },
  { title: 'Evaluating Diagnostic Accuracy in Multimodal Models', source: 'The Lancet Digital Health · 2024', pages: 12, status: 'Indexed', topics: ['Evaluation', 'Vision'], date: 'Yesterday' },
  { title: 'Safety and Reliability of AI-Assisted Diagnosis', source: 'JAMA · 2023', pages: 24, status: 'Indexed', topics: ['Safety', 'Clinical AI'], date: 'May 23' },
  { title: 'Human-AI Collaboration in Radiology', source: 'Radiology · 2024', pages: 9, status: 'Processing', topics: ['Collaboration'], date: 'May 22' },
  { title: 'Benchmarking Medical Vision-Language Models', source: 'arXiv · 2024', pages: 31, status: 'Indexed', topics: ['Benchmarks', 'Vision'], date: 'May 18' },
]

const navGroups = [
  { label: 'Workspace', items: [['overview', 'Overview', LayoutDashboard], ['workspaces', 'Workspaces', FolderKanban], ['documents', 'Documents', FileText], ['map', 'Knowledge Map', Network]] },
  { label: 'Research', items: [['insights', 'Insights', Lightbulb], ['evidence', 'Evidence Explorer', ShieldCheck], ['claim', 'Claim Analysis', GitCompare], ['assistant', 'AI Assistant', Bot]] },
  { label: 'Library', items: [['saved', 'Saved Findings', BookOpen]] },
]

function Badge({ children, tone = 'muted' }: { children: React.ReactNode; tone?: 'muted' | 'blue' | 'amber' | 'green' }) {
  return <span className={`badge badge-${tone}`}>{children}</span>
}

function StatCard({ icon: Icon, label, value, detail, accent }: { icon: typeof Activity; label: string; value: string; detail: string; accent?: string }) {
  return <div className="stat-card"><div className="stat-top"><span className="icon-box"><Icon size={16} /></span><span className="eyebrow">{label}</span><ArrowUpRight size={14} className="muted-icon" /></div><strong className={accent}>{value}</strong><span className="stat-detail">{detail}</span></div>
}

function SectionTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: React.ReactNode }) {
  return <div className="section-title"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h2>{title}</h2></div>{action}</div>
}

function Overview({ go }: { go: (view: View) => void }) {
  return <div className="page-content">
    <div className="welcome-row"><div><div className="eyebrow">TUESDAY, MAY 28, 2024</div><h1>Good morning, Alex.</h1><p className="lede">Your research is moving forward. Here&apos;s what needs your attention.</p></div><button className="button button-primary" onClick={() => go('documents')}><Upload size={16} /> Add documents</button></div>
    <div className="stats-grid"><StatCard icon={FileText} label="Documents" value="128" detail="+12 this month" accent="accent-blue" /><StatCard icon={Network} label="Knowledge nodes" value="2,846" detail="Across 6 workspaces" /><StatCard icon={Lightbulb} label="New insights" value="24" detail="Since your last visit" accent="accent-amber" /><StatCard icon={Activity} label="Evidence score" value="78/100" detail="Collection average" /></div>
    <div className="overview-grid"><div className="panel"><SectionTitle eyebrow="RESEARCH PULSE" title="Your knowledge map" action={<button className="text-button" onClick={() => go('map')}>Explore map <ArrowUpRight size={14} /></button>} /><div className="map-preview"><div className="map-lines" /><div className="node node-main">Clinical AI</div><div className="node node-one">Safety</div><div className="node node-two">LLMs</div><div className="node node-three">Evaluation</div><div className="node node-four">Radiology</div><div className="map-label"><span className="live-dot" /> 2,846 entities connected</div></div></div><div className="panel"><SectionTitle eyebrow="RECENT ACTIVITY" title="Research feed" action={<button className="icon-button" aria-label="More activity"><MoreHorizontal size={18} /></button>} /><div className="activity-list"><ActivityItem icon={Sparkles} title="New connection found" text="Safety ↔ Clinical deployment" time="12 min ago" tone="blue" /><ActivityItem icon={FileText} title="Document indexed" text="Foundation Models for Clinical..." time="1 hr ago" /><ActivityItem icon={GitCompare} title="Potential conflict detected" text="Diagnostic accuracy claims" time="3 hrs ago" tone="amber" /><ActivityItem icon={Users} title="Workspace shared" text="Clinical AI Research" time="Yesterday" /></div></div></div>
    <div className="lower-grid"><div className="panel"><SectionTitle eyebrow="CONTINUE READING" title="Recent documents" action={<button className="text-button" onClick={() => go('documents')}>View all <ArrowUpRight size={14} /></button>} /><DocumentRows compact go={go} /></div><div className="panel insight-panel"><div className="insight-mark"><Lightbulb size={17} /></div><div><div className="eyebrow">COLLECTION INSIGHT</div><h3>Evidence is strongest where human review is explicit</h3><p>Across 18 papers, assisted workflows show more consistent gains than autonomous diagnosis. Explore the supporting evidence.</p><button className="text-button" onClick={() => go('insights')}>Read insight <ArrowUpRight size={14} /></button></div></div></div>
  </div>
}
function ActivityItem({ icon: Icon, title, text, time, tone }: { icon: typeof Activity; title: string; text: string; time: string; tone?: string }) { return <div className="activity-item"><span className={`activity-icon ${tone || ''}`}><Icon size={15} /></span><div><strong>{title}</strong><span>{text}</span></div><time>{time}</time></div> }
function DocumentRows({ compact = false, filter = '', go }: { compact?: boolean; filter?: string; go?: (view: View) => void }) { const list = documents.filter(d => d.title.toLowerCase().includes(filter.toLowerCase())); return <div className="doc-list">{list.slice(0, compact ? 3 : 10).map((doc) => <button className="doc-row" key={doc.title} onClick={() => go?.('document-detail')} aria-label={`Open ${doc.title}`}><span className="file-icon"><FileText size={17} /></span><div className="doc-info"><strong>{doc.title}</strong><span>{doc.source} · {doc.pages} pages</span></div><div className="doc-topics">{doc.topics.map(t => <Badge key={t}>{t}</Badge>)}</div><Badge tone={doc.status === 'Processing' ? 'amber' : 'green'}>{doc.status}</Badge><time>{doc.date}</time><span className="icon-button" aria-hidden="true"><MoreHorizontal size={16} /></span></button>)}</div> }

function DocumentsView({ go }: { go: (view: View) => void }) { const [query, setQuery] = useState(''); const [uploaded, setUploaded] = useState(false); return <div className="page-content"><SectionTitle eyebrow="RESEARCH LIBRARY" title="Documents" action={<button className="button button-primary" onClick={() => setUploaded(true)}><Plus size={16} /> Add documents</button>} /><div className="toolbar"><div className="search-field"><Search size={16} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search documents, topics, authors..." /></div><button className="button button-ghost"><Filter size={15} /> Filters <ChevronDown size={14} /></button><span className="toolbar-count">128 documents</span></div>{uploaded && <div className="upload-banner"><span className="upload-spinner"><Activity size={15} /></span><div><strong>Document intake is ready</strong><span>Drop PDFs here or connect a source. Processing is simulated in this MVP.</span></div><button className="icon-button" onClick={() => setUploaded(false)}><X size={16} /></button></div>}<div className="panel table-panel"><DocumentRows filter={query} go={go} /></div></div> }

function WorkspacesView({ go }: { go: (view: View) => void }) { return <div className="page-content"><SectionTitle eyebrow="YOUR RESEARCH" title="Workspaces" action={<button className="button button-primary"><Plus size={16} /> New workspace</button>} /><div className="workspace-grid">{[['Clinical AI Research','42 documents','1,284 nodes','Updated 12 min ago','blue'],['Foundation Models','31 documents','892 nodes','Updated yesterday','amber'],['AI Safety & Alignment','28 documents','644 nodes','Updated May 23','green'],['Personal Reading List','27 documents','326 nodes','Updated May 18','muted']].map(([name, docs, nodes, updated, tone], i) => <button className="workspace-card" key={name} onClick={() => go('workspace-detail')}><div className={`workspace-symbol ${tone}`}><Hexagon size={20} /></div><div className="workspace-card-head"><h3>{name}</h3><MoreHorizontal size={17} /></div><p>Medical artificial intelligence, evaluation, and deployment research.</p><div className="workspace-meta"><span><FileText size={14} />{docs}</span><span><Network size={14} />{nodes}</span></div><div className="workspace-footer"><span>{updated}</span><ArrowUpRight size={15} /></div></button>)}</div></div> }

function MapView() { const [selected, setSelected] = useState('Clinical AI'); return <div className="page-content"><SectionTitle eyebrow="CLINICAL AI RESEARCH" title="Knowledge map" action={<div className="segmented"><button className="active">Graph</button><button>Clusters</button><button>Timeline</button></div>} /><div className="map-layout"><div className="panel graph-panel"><div className="graph-toolbar"><div className="search-field small"><Search size={15} /><input placeholder="Find a concept..." /></div><Badge tone="blue"><span className="live-dot" /> Live index</Badge><button className="icon-button"><MoreHorizontal size={17} /></button></div><div className="graph-canvas"><div className="graph-grid" /><svg className="edges" viewBox="0 0 760 480" aria-hidden="true"><path d="M380 240L180 130M380 240L570 125M380 240L165 345M380 240L600 350M180 130L570 125M165 345L600 350M180 130L165 345M570 125L600 350" /></svg>{[['Clinical AI',380,240,'main'],['Safety',180,130,'blue'],['LLMs',570,125,'amber'],['Evaluation',165,345,'green'],['Radiology',600,350,'blue'],['Human review',95,220,'muted'],['Reliability',660,210,'amber']].map(([label,x,y,tone]) => <button key={label as string} className={`graph-node ${tone} ${selected === label ? 'selected' : ''}`} style={{ left: `${(x as number) / 7.6}%`, top: `${(y as number) / 4.8}%` }} onClick={() => setSelected(label as string)}>{label}</button>)}</div></div><div className="panel node-detail"><div className="eyebrow">SELECTED CONCEPT</div><h3>{selected}</h3><p>Central topic connected to evidence across your collection.</p><div className="detail-stat"><strong>184</strong><span>mentions</span></div><div className="detail-stat"><strong>42</strong><span>connected sources</span></div><button className="button button-ghost full">View supporting evidence <ArrowUpRight size={15} /></button></div></div></div> }

function InsightsView({ go }: { go: (view: View) => void }) { return <div className="page-content"><SectionTitle eyebrow="FROM YOUR COLLECTION" title="Insights" action={<button className="button button-ghost"><Filter size={15} /> All topics</button>} /><div className="insight-list">{[['Human review changes the reliability equation','Across the collection, human-in-the-loop systems show a consistent improvement in diagnostic calibration. This pattern appears in 8 of 12 evaluated studies.','Strong evidence','18 sources','blue'],['Benchmark gains do not transfer evenly across specialties','Performance improvements are concentrated in high-resource imaging tasks, while rare-disease cohorts remain underrepresented.','Emerging pattern','9 sources','amber'],['Safety metrics are rarely reported alongside accuracy','Only 3 studies report both diagnostic accuracy and prospective safety outcomes, creating a meaningful evidence gap for deployment decisions.','Evidence gap','6 sources','green']].map(([title,text,label,sources,tone]) => <article className="insight-card" key={title}><div className={`insight-icon ${tone}`}><Lightbulb size={18} /></div><div className="insight-body"><div className="eyebrow">COLLECTION-SCOPED FINDING</div><h3>{title}</h3><p>{text}</p><div className="insight-footer"><Badge tone={tone === 'blue' ? 'blue' : tone === 'amber' ? 'amber' : 'green'}>{label}</Badge><span>{sources}</span><button className="text-button" onClick={() => go('evidence')}>Explore evidence <ArrowUpRight size={14} /></button></div></div><button className="icon-button"><BookOpen size={16} /></button></article>)}</div></div> }

function EvidenceView() { return <div className="page-content"><SectionTitle eyebrow="TRACEABLE RESEARCH" title="Evidence explorer" action={<div className="search-field small"><Search size={15} /><input placeholder="Search claims or citations..." /></div>} /><div className="evidence-layout"><div className="panel evidence-list"><div className="eyebrow">TOP CLAIMS IN YOUR COLLECTION</div>{[['Human review improves calibration in clinical AI','0.86','12 citations','High'],['Multimodal models outperform unimodal baselines','0.72','8 citations','Moderate'],['Current benchmarks underrepresent rare conditions','0.64','6 citations','Moderate'],['Autonomous deployment increases operational risk','0.41','4 citations','Limited']].map(([claim,score,citations,strength]) => <button className="claim-row" key={claim}><div className="score-ring">{score}</div><div><strong>{claim}</strong><span>{citations} · Evidence Strength Score</span></div><Badge tone={strength === 'High' ? 'green' : strength === 'Limited' ? 'amber' : 'blue'}>{strength}</Badge><ArrowUpRight size={15} /></button>)}</div><div className="panel citation-panel"><div className="eyebrow">SELECTED EVIDENCE</div><h3>Human review improves calibration in clinical AI</h3><p className="quote">“Assisted decision-making produced more reliable confidence estimates than both unaided clinicians and autonomous model predictions.”</p><div className="citation"><span className="journal-mark">NM</span><div><strong>Foundation Models for Clinical Decision Support</strong><span>Nature Medicine · 2024 · p. 14</span></div></div><div className="citation-tags"><Badge tone="green">Direct support</Badge><Badge>Peer reviewed</Badge></div></div></div></div> }

function ClaimView() { const [claim, setClaim] = useState('AI-assisted diagnosis is safer than autonomous diagnosis.'); const [analyzed, setAnalyzed] = useState(false); return <div className="page-content"><SectionTitle eyebrow="COMPARE AGAINST EVIDENCE" title="Claim analysis" /><div className="claim-layout"><div className="panel claim-input"><div className="eyebrow">YOUR CLAIM</div><textarea value={claim} onChange={e => setClaim(e.target.value)} /><div className="claim-actions"><span><ShieldCheck size={15} /> Grounded in Clinical AI Research</span><button className="button button-primary" onClick={() => setAnalyzed(true)}><Sparkles size={15} /> Analyze claim</button></div></div>{analyzed ? <div className="panel analysis-result"><div className="result-top"><div><div className="eyebrow">EVIDENCE STRENGTH SCORE</div><strong className="big-score">0.58</strong></div><Badge tone="amber">Mixed evidence</Badge></div><p>Your claim is partially supported by the collection. Evidence favors assisted workflows, but does not establish that they are universally safer than autonomous systems.</p><div className="bar-label"><span>Supporting evidence</span><span>7 sources</span></div><div className="progress"><span style={{ width: '68%' }} /></div><div className="bar-label"><span>Contradicting evidence</span><span>3 sources</span></div><div className="progress amber-bar"><span style={{ width: '32%' }} /></div><button className="text-button">Open full evidence trail <ArrowUpRight size={14} /></button></div> : <div className="panel analysis-empty"><GitCompare size={28} /><h3>Analyze a research claim</h3><p>We&apos;ll compare it against indexed sources, surface supporting and conflicting evidence, and show exactly where the strength score comes from.</p></div>}</div></div> }

function AssistantView() { const [message, setMessage] = useState(''); const [sent, setSent] = useState(false); return <div className="page-content assistant-page"><SectionTitle eyebrow="GROUNDED IN YOUR COLLECTION" title="AI Assistant" action={<Badge tone="green"><span className="live-dot" /> Collection connected</Badge>} /><div className="assistant-shell"><div className="chat-area"><div className="assistant-intro"><span className="assistant-avatar"><Bot size={22} /></span><div><h3>Ask your research companion</h3><p>Answers are grounded in your indexed documents and always include an evidence trail.</p></div></div><div className="chat-message user"><span>What are the strongest arguments for human review in clinical AI?</span></div>{sent && <div className="chat-message user"><span>{message}</span></div>}<div className="chat-message assistant"><span>Across your collection, the strongest argument is reliability: human review consistently improves calibration and catches edge cases that benchmark performance alone misses. The evidence is strongest in radiology and high-stakes diagnostic workflows.</span><div className="chat-citations"><span><FileText size={13} /> 8 sources</span><span><ShieldCheck size={13} /> Evidence score 0.86</span></div></div><div className="prompt-box"><textarea value={message} onChange={e => setMessage(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); if (message.trim()) { setSent(true); setMessage('') } } }} placeholder="Ask a question about your research..." /><div className="prompt-footer"><span>Shift + Enter for new line</span><button className="button button-primary" onClick={() => { if (message.trim()) { setSent(true); setMessage('') } }}><ArrowUpRight size={15} /></button></div></div></div><aside className="assistant-side"><div className="eyebrow">SUGGESTED QUESTIONS</div>{['Which studies challenge this claim?','Find gaps in the safety evidence','Compare model performance by specialty'].map(q => <button key={q} className="suggestion" onClick={() => setMessage(q)}>{q}<ArrowUpRight size={14} /></button>)}<div className="assistant-note"><Zap size={15} /><span>Answers are simulated for this MVP. Connect a model and retrieval service to activate live research.</span></div></aside></div></div> }

function WorkspaceDetail({ go }: { go: (view: View) => void }) { return <div className="page-content"><SectionTitle eyebrow="WORKSPACE / CLINICAL AI RESEARCH" title="Clinical AI Research" action={<button className="button button-primary" onClick={() => go('documents')}><Plus size={16} /> Add documents</button>} /><div className="stats-grid"><StatCard icon={FileText} label="Documents" value="42" detail="8 indexed this week" accent="accent-blue" /><StatCard icon={Network} label="Knowledge nodes" value="1,284" detail="+86 this month" /><StatCard icon={Lightbulb} label="Insights" value="18" detail="4 need review" accent="accent-amber" /><StatCard icon={Users} label="Collaborators" value="6" detail="2 active today" /></div><div className="overview-grid"><div className="panel"><SectionTitle eyebrow="WORKSPACE PULSE" title="Research activity" /><div className="activity-list"><ActivityItem icon={FileText} title="New document indexed" text="Foundation Models for Clinical Decision Support" time="12 min ago" tone="blue" /><ActivityItem icon={GitCompare} title="Claim needs review" text="Autonomous diagnosis safety" time="2 hrs ago" tone="amber" /><ActivityItem icon={Lightbulb} title="Insight generated" text="Human review improves calibration" time="Yesterday" tone="blue" /></div></div><div className="panel"><SectionTitle eyebrow="TOPIC COVERAGE" title="Research areas" /><div className="bar-label"><span>Clinical AI</span><span>82%</span></div><div className="progress"><span style={{ width: '82%' }} /></div><div className="bar-label"><span>Safety & reliability</span><span>64%</span></div><div className="progress amber-bar"><span style={{ width: '64%' }} /></div><div className="bar-label"><span>Human collaboration</span><span>48%</span></div><div className="progress"><span style={{ width: '48%' }} /></div></div></div></div> }

function DocumentDetail({ go }: { go: (view: View) => void }) { return <div className="page-content"><button className="text-button" onClick={() => go('documents')}><ArrowUpRight size={14} /> Back to documents</button><SectionTitle eyebrow="DOCUMENT / NATURE MEDICINE · 2024" title="Foundation Models for Clinical Decision Support" action={<Badge tone="green">Indexed</Badge>} /><div className="overview-grid"><div className="panel"><div className="eyebrow">ABSTRACT</div><h3>Foundation models are changing the shape of clinical decision support</h3><p className="lede">This document examines how multimodal systems perform across diagnostic tasks, with a focus on calibration, human oversight, and safe deployment conditions.</p><div className="citation-tags"><Badge tone="blue">Clinical AI</Badge><Badge>18 pages</Badge><Badge>42 mentions</Badge></div></div><div className="panel"><div className="eyebrow">DOCUMENT SIGNALS</div><div className="detail-stat"><strong>0.86</strong><span>Evidence Strength Score</span></div><div className="detail-stat"><strong>14</strong><span>Extracted claims</span></div><button className="button button-primary full" onClick={() => go('evidence')}>Explore evidence <ArrowUpRight size={15} /></button></div></div><div className="panel"><SectionTitle eyebrow="EXTRACTED CLAIMS" title="Key findings" action={<button className="text-button" onClick={() => go('claim')}>Analyze a claim <ArrowUpRight size={14} /></button>} /><div className="claim-row"><div className="score-ring">0.86</div><div><strong>Human review improves confidence calibration</strong><span>Direct support · page 14</span></div><Badge tone="green">Supported</Badge><ArrowUpRight size={15} /></div><div className="claim-row"><div className="score-ring">0.62</div><div><strong>Performance gains vary across specialties</strong><span>Qualified support · page 9</span></div><Badge tone="amber">Mixed</Badge><ArrowUpRight size={15} /></div></div></div> }

function SimpleView({ view }: { view: View }) { const titles: Record<string, [string,string]> = { saved: ['RESEARCH LIBRARY','Saved findings'], settings: ['WORKSPACE PREFERENCES','Settings'] }; const Icon = view === 'saved' ? BookOpen : Settings; return <div className="page-content"><SectionTitle eyebrow={titles[view][0]} title={titles[view][1]} /><div className="panel empty-view"><span className="icon-box"><Icon size={18} /></span><h3>{view === 'saved' ? 'Your saved findings' : 'Workspace settings'}</h3><p>{view === 'saved' ? 'Save insights and evidence trails here as you review your collection.' : 'Manage workspace details, sources, and research preferences.'}</p><button className="button button-primary">{view === 'saved' ? 'Explore insights' : 'Configure workspace'}</button></div></div> }

export default function Page() { const [view, setView] = useState<View>('overview'); const [sidebar, setSidebar] = useState(true); const [dark, setDark] = useState(true); const go = (v: View) => setView(v); const page = useMemo(() => ({ overview: <Overview go={go} />, workspaces: <WorkspacesView go={go} />, 'workspace-detail': <WorkspaceDetail go={go} />, documents: <DocumentsView go={go} />, 'document-detail': <DocumentDetail go={go} />, map: <MapView />, insights: <InsightsView go={go} />, evidence: <EvidenceView />, claim: <ClaimView />, assistant: <AssistantView />, saved: <SimpleView view="saved" />, settings: <SimpleView view="settings" /> }[view]), [view]); return <div className={`app-shell ${dark ? 'dark-shell' : ''}`}><aside className={`sidebar ${sidebar ? '' : 'collapsed'}`}><div className="brand"><span className="brand-mark"><BrainCircuit size={18} /></span>{sidebar && <strong>docu<span>mind</span></strong>}</div><div className="workspace-switcher"><span className="workspace-dot" />{sidebar && <><span>Clinical AI Research</span><ChevronDown size={14} /></>}</div><nav>{navGroups.map(group => <div className="nav-group" key={group.label}><div className="nav-label">{sidebar && group.label}</div>{group.items.map(([id, label, Icon]) => <button key={id as string} className={`nav-item ${view === id ? 'active' : ''}`} onClick={() => go(id as View)} title={label as string}><Icon size={17} />{sidebar && <span>{label as string}</span>}{sidebar && id === 'insights' && <span className="nav-count">24</span>}</button>)}</div>)} </nav><div className="sidebar-bottom"><button className={`nav-item ${view === 'settings' ? 'active' : ''}`} onClick={() => go('settings')}><Settings size={17} />{sidebar && <span>Settings</span>}</button><div className="profile"><span className="avatar">AS</span>{sidebar && <div><strong>Alex Smith</strong><span>Researcher</span></div>}{sidebar && <MoreHorizontal size={16} />}</div></div></aside><main className="main-area"><header className="topbar"><button className="icon-button menu-button" onClick={() => setSidebar(!sidebar)} aria-label="Toggle sidebar"><Menu size={19} /></button><div className="breadcrumb"><span>Clinical AI Research</span><span>/</span><strong>{view === 'overview' ? 'Overview' : navGroups.flatMap(g => g.items).find(i => i[0] === view)?.[1] || view}</strong></div><div className="top-actions"><div className="global-search"><Search size={16} /><span>Search anything</span><kbd>⌘ K</kbd></div><button className="icon-button" aria-label="Help"><CircleHelp size={18} /></button><button className="icon-button notification" aria-label="Notifications"><Bell size={18} /><i /></button><button className="icon-button" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Sun size={18} /> : <Moon size={18} />}</button></div></header>{page}</main></div> }
